set -g status off
set -g prefix M-Tab

unbind C-b

bind q kill-window
bind C new-session
bind-key f new-window -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind x confirm-before -p "kill other windows? (y/n)" "kill-window -a" 
bind Q confirm-before -p "kill-session #S? (y/n)" kill-session
bind w choose-tree -Zs

unbind -T copy-mode-vi h
unbind -T copy-mode-vi j
unbind -T copy-mode-vi k
unbind -T copy-mode-vi l
unbind -T copy-mode-vi e
unbind -T copy-mode-vi m
unbind -T copy-mode-vi n
unbind -T copy-mode-vi i
unbind -T copy-mode-vi k

unbind -T copy-mode-vi C-u
unbind -T copy-mode-vi C-d

bind-key -T copy-mode-vi C-n send-keys -X halfpage-down \; send-keys -X scroll-middle
bind-key -T copy-mode-vi C-e send-keys -X halfpage-up \; send-keys -X scroll-middle

bind -T copy-mode-vi m send-keys -X cursor-left
bind -T copy-mode-vi n send-keys -X cursor-down \; send-keys -X scroll-middle
bind -T copy-mode-vi e send-keys -X cursor-up \; send-keys -X scroll-middle
bind -T copy-mode-vi i send-keys -X cursor-right

bind -T copy-mode-vi k send-keys -X search-again \; send-keys -X scroll-middle
bind -T copy-mode-vi h send-keys -X next-word-end

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

set-window-option -g mode-keys vi
set-option -g default-terminal 'tmux-256color'
set-option -sa terminal-overrides ",alacritty*:Tc"
set -g detach-on-destroy off
