hl.env("XCURSOR_SIZE", "40")
hl.env("XCURSOR_THEME", "BreezeX-RosePine-Linux")
hl.env("HYPRCURSOR_SIZE", "40")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")
-- hl.env("PATH", "$HOME/appimage:$HOME/bash:$PATH")
hl.env("QT_IM_MODULE", "wayland;fcitx")
hl.env("GTK_THEME", "Adapta:dark")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_SCALE_FACTOR", "1.5")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "0")
