[font]
size = 25

[font.bold]
family = "source code pro"
style = "Bold"

[font.bold_italic]
family = "source code pro"
style = "Bold Italic"

[font.italic]
family = "source code pro"
style = "Italic"

[font.normal]
family = "source code pro"
style = "Regular"

[colors]
transparent_background_colors = true
[colors.primary]
background = "#11121a"

[window]
opacity = 0.95
